theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: ¡Bienvenido al repositorio de la asignatura Usabilidad y Accesibilidad!
description: En este repositorio se pueden encontrar los diferentes trabajos realizados a lo largo de la asignatura.
